image: fpco/stack-build:lts

test:8.2:
  script:
    - stack --no-terminal --resolver nightly-2017-07-31 --install-ghc test

test:8.0:
  script:
    - stack --no-terminal --resolver lts-9 --install-ghc test

test:7.10:
  script:
    - stack --no-terminal --resolver lts-6 --install-ghc test

test:7.8:
  script:
    - stack --no-terminal --resolver lts-2 --install-ghc test

